# Generated by Django 3.2 on 2021-04-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20210421_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiedcv',
            name='degree_1',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
