# Generated by Django 3.2 on 2021-04-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_qualifiedcv_degree_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifiedcv',
            name='date_of_birth',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='unqualifiedcv',
            name='date_of_birth',
            field=models.CharField(max_length=12),
        ),
    ]
