# Generated by Django 3.2 on 2021-04-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20210423_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unqualifiedcv',
            old_name='accept',
            new_name='accepted_by_hod',
        ),
        migrations.AddField(
            model_name='unqualifiedcv',
            name='accepted_by_hr',
            field=models.BooleanField(default=False),
        ),
    ]
