# Generated by Django 3.2 on 2021-04-23 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20210423_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifiedcv',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unqualifiedcv',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
