# Generated by Django 3.2 on 2021-04-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_unqualifiedcv_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifiedcv',
            name='job_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unqualifiedcv',
            name='job_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
