from django.contrib import admin
from .models import QualifiedCv, UnQualifiedCv
# Register your models here.
class QualifiedCvAdmin(admin.ModelAdmin):
	list_display = [
		'id',
		'candidate_name',
		# 'nationality',
		'gender',
		'cell_no',
		'experience_period_1',
		'paid',
		'accepted_by_hod',
		'accepted_by_hr',
		'job_confirm',
	]
	# list_editable = [
	# 	'accepted_by_hod',
	# 	'accepted_by_hr',
	# ]
	readonly_fields = [
		'paid',
		'time_submitted',

		'candidate_name',
		'guardian_name',
		'nationality',
		'gender',
		'date_of_birth',
		'domicile',
		'permanent_address',
		'present_address',
		'land_line_no',
		'office_no',
		'cell_no',
		'email',
		'cnic',

		'degree_1',
		'degree_date_1',
		'degree_institue_1',
		'degree_specialization_1',
		'degree_grade_1',
		'degree_2',
		'degree_date_2',
		'degree_institue_2',
		'degree_specialization_2',
		'degree_grade_2',
		'degree_3',
		'degree_date_3',
		'degree_institue_3',
		'degree_specialization_3',
		'degree_grade_3',

		'training_institution_1',
		'training_course_1',
		'training_diploma_1',
		'training_field_1',
		'training_remarks_1',
		'training_institution_2',
		'training_course_2',
		'training_diploma_2',
		'training_field_2',
		'training_remarks_2',
		'training_institution_3',
		'training_course_3',
		'training_diploma_3',
		'training_field_3',
		'training_remarks_3',

		'experience_institution_1',
		'experience_designation_1',
		'experience_payscale_1',
		'experience_job_1',
		'experience_period_1',
		'experience_institution_2',
		'experience_designation_2',
		'experience_payscale_2',
		'experience_job_2',
		'experience_period_2',
		'experience_institution_3',
		'experience_designation_3',
		'experience_payscale_3',
		'experience_job_3',
		'experience_period_3',

		'extra_activities',
		'reference_phone_1',
		'reference_phone_2',
		'reference_position_1',
		'reference_position_2',
		'reference_residence_1',
		'reference_residence_2',
	]
	list_filter = [
		'experience_period_1',
		'gender',
		'time_submitted',
		'paid',
		'accepted_by_hod',
	]
admin.site.register(QualifiedCv, QualifiedCvAdmin)
class UnQualifiedCvAdmin(admin.ModelAdmin):
	list_display = [
		'id',
		'candidate_name',
		# 'nationality',
		'gender',
		'cell_no',
		'degree_1',
		'experience_period_1',
		'paid',
		'accepted_by_hod',
		'accepted_by_hr',
		'job_confirm'
	]
	readonly_fields = [
		'paid',
		'time_submitted',

		'candidate_name',
		'guardian_name',
		'nationality',
		'gender',
		'date_of_birth',
		'domicile',
		'permanent_address',
		'present_address',
		'land_line_no',
		'office_no',
		'cell_no',
		'email',
		'cnic',

		'degree_1',
		'degree_date_1',
		'degree_institue_1',
		'degree_specialization_1',
		'degree_grade_1',
		'degree_2',
		'degree_date_2',
		'degree_institue_2',
		'degree_specialization_2',
		'degree_grade_2',
		'degree_3',
		'degree_date_3',
		'degree_institue_3',
		'degree_specialization_3',
		'degree_grade_3',

		'training_institution_1',
		'training_course_1',
		'training_diploma_1',
		'training_field_1',
		'training_remarks_1',
		'training_institution_2',
		'training_course_2',
		'training_diploma_2',
		'training_field_2',
		'training_remarks_2',
		'training_institution_3',
		'training_course_3',
		'training_diploma_3',
		'training_field_3',
		'training_remarks_3',

		'experience_institution_1',
		'experience_designation_1',
		'experience_payscale_1',
		'experience_job_1',
		'experience_period_1',
		'experience_institution_2',
		'experience_designation_2',
		'experience_payscale_2',
		'experience_job_2',
		'experience_period_2',
		'experience_institution_3',
		'experience_designation_3',
		'experience_payscale_3',
		'experience_job_3',
		'experience_period_3',

		'extra_activities',
		'reference_phone_1',
		'reference_phone_2',
		'reference_position_1',
		'reference_position_2',
		'reference_residence_1',
		'reference_residence_2',
	]

	list_filter = [
		'experience_period_1',
		'gender',
		'time_submitted',
		'paid',
		'accepted_by_hod',
	]
admin.site.register(UnQualifiedCv, UnQualifiedCvAdmin)