from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.
class QualifiedCv(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	time_submitted = models.DateTimeField(auto_now_add=True)
	paid = models.BooleanField(default=False)
	accepted_by_hod = models.BooleanField(default=False)
	accepted_by_hr = models.BooleanField(default=False)
	job_confirm = models.BooleanField(default=False)
	candidate_name = models.CharField(max_length=256, null=True, default='')
	guardian_name = models.CharField(max_length=256, null=True, default='')
	nationality = models.CharField(max_length=256, null=True, default='')
	gender = models.CharField(max_length=256, null=True, default='')
	date_of_birth = models.DateField()
	domicile = models.CharField(max_length=256, null=True, default='')
	permanent_address = models.CharField(max_length=256, null=True, default='')
	present_address = models.CharField(max_length=256, null=True, default='')
	land_line_no = models.CharField(max_length=256, null=True, default='')
	office_no = models.CharField(max_length=256, null=True, default='')
	cell_no = models.CharField(max_length=256, null=True, default='')
	email = models.EmailField(max_length=256, null=True, default='')
	cnic = models.CharField(max_length=13, null=True, default='')

	degree_1 = models.CharField(max_length=1)
	degree_date_1 = models.CharField(max_length=256, null=True, default='')
	degree_institue_1 = models.CharField(max_length=256, null=True, default='')
	degree_specialization_1 = models.CharField(max_length=256, null=True, default='')
	degree_grade_1 = models.CharField(max_length=256, null=True, default='')
	degree_2 = models.CharField(max_length=1, null=True, default='')
	degree_date_2 = models.CharField(max_length=256, null=True, default='')
	degree_institue_2 = models.CharField(max_length=256, null=True, default='')
	degree_specialization_2 = models.CharField(max_length=256, null=True, default='')
	degree_grade_2 = models.CharField(max_length=256, null=True, default='')
	degree_3 = models.CharField(max_length=1, null=True, default='')
	degree_date_3 = models.CharField(max_length=256, null=True, default='')
	degree_institue_3 = models.CharField(max_length=256, null=True, default='')
	degree_specialization_3 = models.CharField(max_length=256, null=True, default='')
	degree_grade_3 = models.CharField(max_length=256, null=True, default='')

	training_institution_1 = models.CharField(max_length=256, null=True, default='')
	training_course_1 = models.CharField(max_length=256, null=True, default='')
	training_diploma_1 = models.CharField(max_length=256, null=True, default='')
	training_field_1 = models.CharField(max_length=256, null=True, default='')
	training_remarks_1 = models.CharField(max_length=256, null=True, default='')
	training_institution_2 = models.CharField(max_length=256, null=True, default='')
	training_course_2 = models.CharField(max_length=256, null=True, default='')
	training_diploma_2 = models.CharField(max_length=256, null=True, default='')
	training_field_2 = models.CharField(max_length=256, null=True, default='')
	training_remarks_2 = models.CharField(max_length=256, null=True, default='')
	training_institution_3 = models.CharField(max_length=256, null=True, default='')
	training_course_3 = models.CharField(max_length=256, null=True, default='')
	training_diploma_3 = models.CharField(max_length=256, null=True, default='')
	training_field_3 = models.CharField(max_length=256, null=True, default='')
	training_remarks_3 = models.CharField(max_length=256, null=True, default='')

	experience_institution_1 = models.CharField(max_length=256, null=True, default='')
	experience_designation_1 = models.CharField(max_length=256, null=True, default='')
	experience_payscale_1 = models.CharField(max_length=256, null=True, default='')
	experience_job_1 = models.CharField(max_length=256, null=True, default='')
	experience_period_1 = models.CharField(max_length=256, null=True, default='')
	experience_institution_2 = models.CharField(max_length=256, null=True, default='')
	experience_designation_2 = models.CharField(max_length=256, null=True, default='')
	experience_payscale_2 = models.CharField(max_length=256, null=True, default='')
	experience_job_2 = models.CharField(max_length=256, null=True, default='')
	experience_period_2 = models.CharField(max_length=256, null=True, default='')
	experience_institution_3 = models.CharField(max_length=256, null=True, default='')
	experience_designation_3 = models.CharField(max_length=256, null=True, default='')
	experience_payscale_3 = models.CharField(max_length=256, null=True, default='')
	experience_job_3 = models.CharField(max_length=256, null=True, default='')
	experience_period_3 = models.CharField(max_length=256, null=True, default='')

	extra_activities = models.TextField(null=True, default='')

	reference_phone_1 = models.CharField(max_length=256, null=True, default='')
	reference_phone_2 = models.CharField(max_length=256, null=True, default='')
	reference_position_1 = models.CharField(max_length=256, null=True, default='')
	reference_position_2 = models.CharField(max_length=256, null=True, default='')
	reference_residence_1 = models.CharField(max_length=256, null=True, default='')
	reference_residence_2 = models.CharField(max_length=256, null=True, default='')
	file = models.FileField(upload_to='files')


class UnQualifiedCv(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	time_submitted = models.DateTimeField(auto_now_add=True)
	paid = models.BooleanField(default=False)
	accepted_by_hod = models.BooleanField(default=False)
	accepted_by_hr = models.BooleanField(default=False)
	job_confirm = models.BooleanField(default=False)
	candidate_name = models.CharField(max_length=256, null=True, default='')
	guardian_name = models.CharField(max_length=256, null=True, default='')
	nationality = models.CharField(max_length=256, null=True, default='')
	gender = models.CharField(max_length=256, null=True, default='')
	date_of_birth = models.DateField()
	domicile = models.CharField(max_length=256, null=True, default='')
	permanent_address = models.CharField(max_length=256, null=True, default='')
	present_address = models.CharField(max_length=256, null=True, default='')
	land_line_no = models.CharField(max_length=256, null=True, default='')
	office_no = models.CharField(max_length=256, null=True, default='')
	cell_no = models.CharField(max_length=256, null=True, default='')
	email = models.EmailField(max_length=256, null=True, default='')
	cnic = models.CharField(max_length=13, null=True, default='')

	degree_1 = models.CharField(max_length=1, null=True, default='')
	degree_date_1 = models.CharField(max_length=256, null=True, default='')
	degree_institue_1 = models.CharField(max_length=256, null=True, default='')
	degree_specialization_1 = models.CharField(max_length=256, null=True, default='')
	degree_grade_1 = models.CharField(max_length=256, null=True, default='')
	degree_2 = models.CharField(max_length=1, null=True, default='')
	degree_date_2 = models.CharField(max_length=256, null=True, default='')
	degree_institue_2 = models.CharField(max_length=256, null=True, default='')
	degree_specialization_2 = models.CharField(max_length=256, null=True, default='')
	degree_grade_2 = models.CharField(max_length=256, null=True, default='')
	degree_3 = models.CharField(max_length=1, null=True, default='')
	degree_date_3 = models.CharField(max_length=256, null=True, default='')
	degree_institue_3 = models.CharField(max_length=256, null=True, default='')
	degree_specialization_3 = models.CharField(max_length=256, null=True, default='')
	degree_grade_3 = models.CharField(max_length=256, null=True, default='')

	training_institution_1 = models.CharField(max_length=256, null=True, default='')
	training_course_1 = models.CharField(max_length=256, null=True, default='')
	training_diploma_1 = models.CharField(max_length=256, null=True, default='')
	training_field_1 = models.CharField(max_length=256, null=True, default='')
	training_remarks_1 = models.CharField(max_length=256, null=True, default='')
	training_institution_2 = models.CharField(max_length=256, null=True, default='')
	training_course_2 = models.CharField(max_length=256, null=True, default='')
	training_diploma_2 = models.CharField(max_length=256, null=True, default='')
	training_field_2 = models.CharField(max_length=256, null=True, default='')
	training_remarks_2 = models.CharField(max_length=256, null=True, default='')
	training_institution_3 = models.CharField(max_length=256, null=True, default='')
	training_course_3 = models.CharField(max_length=256, null=True, default='')
	training_diploma_3 = models.CharField(max_length=256, null=True, default='')
	training_field_3 = models.CharField(max_length=256, null=True, default='')
	training_remarks_3 = models.CharField(max_length=256, null=True, default='')

	experience_institution_1 = models.CharField(max_length=256, null=True, default='')
	experience_designation_1 = models.CharField(max_length=256, null=True, default='')
	experience_payscale_1 = models.CharField(max_length=256, null=True, default='')
	experience_job_1 = models.CharField(max_length=256, null=True, default='')
	experience_period_1 = models.CharField(max_length=256, null=True, default='')
	experience_institution_2 = models.CharField(max_length=256, null=True, default='')
	experience_designation_2 = models.CharField(max_length=256, null=True, default='')
	experience_payscale_2 = models.CharField(max_length=256, null=True, default='')
	experience_job_2 = models.CharField(max_length=256, null=True, default='')
	experience_period_2 = models.CharField(max_length=256, null=True, default='')
	experience_institution_3 = models.CharField(max_length=256, null=True, default='')
	experience_designation_3 = models.CharField(max_length=256, null=True, default='')
	experience_payscale_3 = models.CharField(max_length=256, null=True, default='')
	experience_job_3 = models.CharField(max_length=256, null=True, default='')
	experience_period_3 = models.CharField(max_length=256, null=True, default='')

	extra_activities = models.TextField(null=True, default='')

	reference_phone_1 = models.CharField(max_length=256, null=True, default='')
	reference_phone_2 = models.CharField(max_length=256, null=True, default='')
	reference_position_1 = models.CharField(max_length=256, null=True, default='')
	reference_position_2 = models.CharField(max_length=256, null=True, default='')
	reference_residence_1 = models.CharField(max_length=256, null=True, default='')
	reference_residence_2 = models.CharField(max_length=256, null=True, default='')

	file = models.FileField(upload_to='files',)